### ISSUE TITLE
Potential security vulnerability

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/ios-inventory-library#121]
We found a potential security vulnerability in one of your dependencies.
A dependency defined in package-lock.json has known security vulnerabilities and should be updated.

**Comment by Fabianopb** [comment]
Hi @ajsb85 I'd be glad to submit a PR for this one!

**Comment by Fabianopb** [comment]
That was fast (and luckly sage, due to the low severity of deps) with `npm audit fix`: https://github.com/flyve-mdm/ios-inventory-library/pull/122

**Comment by ajsb85** [comment]
Hi, @Fabianopb 
Thank you for your contribution.
